import React from 'react';
import { 
  LayoutDashboard, 
  FileText, 
  Settings, 
  Bell, 
  Search, 
  Menu, 
  X,
  TrendingUp,
  DollarSign,
  Upload,
  Plus,
  Trash2,
  Save,
  Download,
  CheckCircle,
  AlertCircle,
  Image as ImageIcon,
  ChevronLeft,
  Activity,
  TrendingDown,
  Sparkles,
  ArrowRight,
  Camera
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  FileText: FileText,
  Settings: Settings,
  Bell: Bell,
  Search: Search,
  Menu: Menu,
  Close: X,
  TrendingUp: TrendingUp,
  DollarSign: DollarSign,
  Upload: Upload,
  Plus: Plus,
  Trash: Trash2,
  Save: Save,
  Download: Download,
  Check: CheckCircle,
  Alert: AlertCircle,
  Image: ImageIcon,
  Back: ChevronLeft,
  Activity: Activity,
  TrendingDown: TrendingDown,
  Sparkles: Sparkles,
  ArrowRight: ArrowRight,
  Camera: Camera
};